/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SneakersIndexImport } from './routes/sneakers/index'

// Create Virtual Routes

const ProfileLazyImport = createFileRoute('/profile')()
const FavouritesLazyImport = createFileRoute('/favourites')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const SneakersSneakeridLazyImport = createFileRoute('/sneakers/$sneakerid')()
const AuthSignupLazyImport = createFileRoute('/auth/signup')()
const AuthSigninLazyImport = createFileRoute('/auth/signin')()

// Create/Update Routes

const ProfileLazyRoute = ProfileLazyImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const FavouritesLazyRoute = FavouritesLazyImport.update({
  path: '/favourites',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/favourites.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SneakersIndexRoute = SneakersIndexImport.update({
  path: '/sneakers/',
  getParentRoute: () => rootRoute,
} as any)

const SneakersSneakeridLazyRoute = SneakersSneakeridLazyImport.update({
  path: '/sneakers/$sneakerid',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/sneakers/$sneakerid.lazy').then((d) => d.Route),
)

const AuthSignupLazyRoute = AuthSignupLazyImport.update({
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/signup.lazy').then((d) => d.Route))

const AuthSigninLazyRoute = AuthSigninLazyImport.update({
  path: '/auth/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/signin.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/favourites': {
      preLoaderRoute: typeof FavouritesLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/signin': {
      preLoaderRoute: typeof AuthSigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      preLoaderRoute: typeof AuthSignupLazyImport
      parentRoute: typeof rootRoute
    }
    '/sneakers/$sneakerid': {
      preLoaderRoute: typeof SneakersSneakeridLazyImport
      parentRoute: typeof rootRoute
    }
    '/sneakers/': {
      preLoaderRoute: typeof SneakersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  FavouritesLazyRoute,
  ProfileLazyRoute,
  AuthSigninLazyRoute,
  AuthSignupLazyRoute,
  SneakersSneakeridLazyRoute,
  SneakersIndexRoute,
])

/* prettier-ignore-end */
