/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SneakersIndexImport } from './routes/sneakers/index'

// Create Virtual Routes

const ProfileLazyImport = createFileRoute('/profile')()
const PolicyLazyImport = createFileRoute('/policy')()
const OfferLazyImport = createFileRoute('/offer')()
const FavouritesLazyImport = createFileRoute('/favourites')()
const AgreementLazyImport = createFileRoute('/agreement')()
const IndexLazyImport = createFileRoute('/')()
const OrdersIndexLazyImport = createFileRoute('/orders/')()
const SneakersSneakeridLazyImport = createFileRoute('/sneakers/$sneakerid')()
const OrdersCreateLazyImport = createFileRoute('/orders/create')()
const AuthSignupLazyImport = createFileRoute('/auth/signup')()
const AuthSigninLazyImport = createFileRoute('/auth/signin')()

// Create/Update Routes

const ProfileLazyRoute = ProfileLazyImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const PolicyLazyRoute = PolicyLazyImport.update({
  path: '/policy',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/policy.lazy').then((d) => d.Route))

const OfferLazyRoute = OfferLazyImport.update({
  path: '/offer',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/offer.lazy').then((d) => d.Route))

const FavouritesLazyRoute = FavouritesLazyImport.update({
  path: '/favourites',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/favourites.lazy').then((d) => d.Route))

const AgreementLazyRoute = AgreementLazyImport.update({
  path: '/agreement',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/agreement.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const OrdersIndexLazyRoute = OrdersIndexLazyImport.update({
  path: '/orders/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/orders/index.lazy').then((d) => d.Route))

const SneakersIndexRoute = SneakersIndexImport.update({
  path: '/sneakers/',
  getParentRoute: () => rootRoute,
} as any)

const SneakersSneakeridLazyRoute = SneakersSneakeridLazyImport.update({
  path: '/sneakers/$sneakerid',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/sneakers/$sneakerid.lazy').then((d) => d.Route),
)

const OrdersCreateLazyRoute = OrdersCreateLazyImport.update({
  path: '/orders/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/orders/create.lazy').then((d) => d.Route))

const AuthSignupLazyRoute = AuthSignupLazyImport.update({
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/signup.lazy').then((d) => d.Route))

const AuthSigninLazyRoute = AuthSigninLazyImport.update({
  path: '/auth/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/signin.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/agreement': {
      preLoaderRoute: typeof AgreementLazyImport
      parentRoute: typeof rootRoute
    }
    '/favourites': {
      preLoaderRoute: typeof FavouritesLazyImport
      parentRoute: typeof rootRoute
    }
    '/offer': {
      preLoaderRoute: typeof OfferLazyImport
      parentRoute: typeof rootRoute
    }
    '/policy': {
      preLoaderRoute: typeof PolicyLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/signin': {
      preLoaderRoute: typeof AuthSigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      preLoaderRoute: typeof AuthSignupLazyImport
      parentRoute: typeof rootRoute
    }
    '/orders/create': {
      preLoaderRoute: typeof OrdersCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/sneakers/$sneakerid': {
      preLoaderRoute: typeof SneakersSneakeridLazyImport
      parentRoute: typeof rootRoute
    }
    '/sneakers/': {
      preLoaderRoute: typeof SneakersIndexImport
      parentRoute: typeof rootRoute
    }
    '/orders/': {
      preLoaderRoute: typeof OrdersIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AgreementLazyRoute,
  FavouritesLazyRoute,
  OfferLazyRoute,
  PolicyLazyRoute,
  ProfileLazyRoute,
  AuthSigninLazyRoute,
  AuthSignupLazyRoute,
  OrdersCreateLazyRoute,
  SneakersSneakeridLazyRoute,
  SneakersIndexRoute,
  OrdersIndexLazyRoute,
])

/* prettier-ignore-end */
